### PR TITLE
Explicitly mention Alternate Domain Names field

### PR DESCRIPTION
**Pull request by OzzieOrca**
*Issue #, if available:*
Originally struggled with this at https://github.com/aws-amplify/amplify-console/issues/512#issuecomment-639892355

*Description of changes:*
Make it more explicit that the Alternate Domain Names (CNAMEs) field in the Cloudfront console causes the CNAMEAlreadyExistsException error.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by KristinaPeterson** [comment]
Thank you for telling us about this issue. A member of the team will be working on it and will provide updates here about progress.

**Comment by OzzieOrca** [comment]
@KristinaPeterson Thanks for merging this :) Although it appears master was updated and your merge just kept what was on master. I still think my extra sentence was valuable and clarified the solution. The current docs say check Cloudfront but then go on to talk about CNAME records which is a setting in Route53/whatever DNS server you have. I think directing people to the `Alternate Domain Names (CNAMEs)` field explicitly is valuable as that is what throws this error. It's the Alternate Domain Name field that causes this error not a CNAME record pointing to the Cloudfront distribution.

Let me know if you'd like me to make another PR.

**Comment by KristinaPeterson** [comment]
@OzzieOrca My apologies - thank you for catching my mistake. We keep this doc set in sync with our public docs on Amazon.com. This topic had been updated since you submitted your PR and I was trying to address the merge conflict and your PR at the same time. I agree that your PR is important to add. To conform to our style guide, I am expanding your suggestion into detailed sub steps that describe how to navigate the Cloudfront console and remove the domain name. I will push this change out to github this week and you will be able to see your PR content here.

**Comment by OzzieOrca** [comment]
Thanks for updating the docs! The new docs seem much more helpful 🎉 https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error

**Pull request merged**
